// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtLkomFgBRc66BQDMbTKNecHjSN1V_XyE',
    appId: '1:1074737376539:web:281b55aab7756bc52ef7be',
    messagingSenderId: '1074737376539',
    projectId: 'rosefam-83009',
    authDomain: 'rosefam-83009.firebaseapp.com',
    databaseURL: 'https://rosefam-83009-default-rtdb.firebaseio.com',
    storageBucket: 'rosefam-83009.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9a_YKDbdEYZOs_3-aJ7UR7bxyNFIG7TE',
    appId: '1:1074737376539:android:b1085648e13a5d232ef7be',
    messagingSenderId: '1074737376539',
    projectId: 'rosefam-83009',
    databaseURL: 'https://rosefam-83009-default-rtdb.firebaseio.com',
    storageBucket: 'rosefam-83009.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5gmq36MX6J9Tz8xwHw5SSyxFgcQgWeE4',
    appId: '1:1074737376539:ios:09e40b5df2b269d22ef7be',
    messagingSenderId: '1074737376539',
    projectId: 'rosefam-83009',
    databaseURL: 'https://rosefam-83009-default-rtdb.firebaseio.com',
    storageBucket: 'rosefam-83009.appspot.com',
    iosBundleId: 'com.rosefam.rosefam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5gmq36MX6J9Tz8xwHw5SSyxFgcQgWeE4',
    appId: '1:1074737376539:ios:09e40b5df2b269d22ef7be',
    messagingSenderId: '1074737376539',
    projectId: 'rosefam-83009',
    databaseURL: 'https://rosefam-83009-default-rtdb.firebaseio.com',
    storageBucket: 'rosefam-83009.appspot.com',
    iosBundleId: 'com.rosefam.rosefam',
  );
}
